# Site settings
baseurl = "https://private-deer-12615.netlify.com/"
languageCode = "en-us"
title = "Konniam Chan"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
    name = "Konniam Chan"
    description = "Konniam's Blog"
    bio = "Data Scientist & Photographer"
    # Enter optionally your twitter account
    twitter = "konniamchan"
    enableRSS = true

    # Integrate Javascript files or stylesheets by adding the url to the external assets or by
    # linking local files with their path relative to the static folder, e.g. "css/styles.css"
    customCSS = []
    customJS  = []

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    home = ""
    subscribe = "RSS"
    # Pagination links
    olderPosts = ""
    newerPosts = ""
    readMore = ""
    copyright = "© 2017 Konniam Chan"
    # Sharing options and author information in posts
    aboutAuthor = "Data Scientist & Photographer"
    tweet = ""
    share = ""
    # 404 page
    title404 = ""
    subtitle404 = ""

    # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
    iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    githubalt  = "https://www.github.com/konniamchan"
    twitter  = "https://www.twitter.com/konniamchan"
    linkedin = "https://www.linkedin.com/in/konniamchan"
